### PR TITLE
Fixed typo

### PR DESCRIPTION
**Pull request by zuphilip**
algorthim instead of algorithm

### CODE REVIEW

**Comment by zuphilip** [comment]
I can squash them together

**Comment by zuphilip** [comment]
Done

**Comment by stweil** [comment]
@zuphilip, looks good, can be pulled.

**Comment by zuphilip** [comment]
Agree. I will let @kba do the merge.

**Comment by kba** [comment]
Thank you

**Comment by zuphilip** [comment]
( OFF-Topic:

@stweil BTW codespell didn't found the `algorthim` spelling mistake because it contained only the plural `algorthims` in its dictionary. Can you fix/add that?

)

**Comment by stweil** [comment]
@zuphilip: yes :-)

**Pull request merged**
