### PR TITLE
explained the different methods in more detail; changed repository fo…

### PR DESCRIPTION
**Pull request by bolandka**
…r creating issues to infolis-web

see https://github.com/infolis/infolis-web/issues/22

I left out the syntax-highlight tool in my description, I wasn't sure about its purpose. Maybe someone can add a few words about that?

### CODE REVIEW

**Comment by kba** [comment]
I don't think the syntax-highlighting thing must be documented at this point. I'm using that for highlighting RDF and TSON. But since the whole API explorer is geared towards developers and power users, it's nice to have it there to try out.

**Comment by kba** [comment]
I changed the wording a bit here https://github.com/infolis/infolis-web/commit/6142762312f8b909c5a362bd9513a55b14480f4d What do you think?

**Comment by bolandka** [comment]
Perfect! (haha, I typed Id instead of ld, good thing you noticed that ;) )

**Comment by kba** [comment]
Homoglyphs are an inifinite source of joy. I and l, 0 and O and quotes and non-standard spaces etc. pp. :confused: 

Anyway, I'll merge these changes, thanks.

**Pull request merged**
